### ISSUE TITLE
Different input return totally same result

### ISSUE THREAD

**Issue by YahooKID** [ICTMCG/Make-Your-Anchor#6]
Thanks for open source,

Here is a little problem, I can't make sure whether it's a bug or features of model.
I pull the code and setup the environment. And the demo has been repeated successfully.
However, when I try to change the appearance image, the body infer model has return me the totally same result, when the clip embedding is different obviously. 
I wanna to make sure whether it's a bug or a feature, or somewhere I did was wrong.

**Comment by bone-11** [comment]
Thanks for your attention.

**Comment by bone-11** [comment]
Thank you for your attention.

As a person-specific approach, each of our model blinds with one specific appearance during fine-tuning stage. If you want to generate other appearances, further fine-tuning is necessary. This training setup is partly due to limitations in both data and computational resources of ours.
To help training other appearance, we plan to release the pre-trained weight from pre-training stage, and the fine-tuning code. The guidance and code for preprocess training data will be updated further.

**Comment by kike-0304** [comment]
> Thank you for your attention.
> 
> As a person-specific approach, each of our model blinds with one specific appearance during fine-tuning stage. If you want to generate other appearances, further fine-tuning is necessary. This training setup is partly due to limitations in both data and computational resources of ours. To help training other appearance, we plan to release the pre-trained weight from pre-training stage, and the fine-tuning code. The guidance and code for preprocess training data will be updated further.

great
